"""Add CRM models

Revision ID: 2c77585b56bd
Revises: f925534d3a76
Create Date: 2026-06-10 11:37:46.283430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2c77585b56bd'
down_revision: Union[str, None] = 'f925534d3a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotizaciones',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('origen', sa.Enum('CATALOGO', 'CONTACTO_INDIVIDUAL', 'CONTACTO_GRUPAL', 'MANUAL', name='origencotizacion'), nullable=False),
    sa.Column('estado', sa.Enum('NUEVA', 'EN_PROCESO', 'CERRADA_EXITO', 'CERRADA_PERDIDA', name='estadocotizacion'), nullable=False),
    sa.Column('mensaje', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo_grupo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cantidad_aprox', sa.Integer(), nullable=True),
    sa.Column('fecha_evento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transporte', sa.Enum('STARKEN', 'CORREOS_DE_CHILE', 'CHILEXPRESS', 'RETIRO_LOCAL', 'OTRO', name='tipotransporte'), nullable=True),
    sa.Column('tipo_despacho', sa.Enum('DOMICILIO', 'SUCURSAL', name='tipodespacho'), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('comuna', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotizaciones_persona_id'), 'cotizaciones', ['persona_id'], unique=False)
    op.create_table('cotizacion_items',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('cotizacion_id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario_estimado', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotizacion_items_cotizacion_id'), 'cotizacion_items', ['cotizacion_id'], unique=False)
    op.create_index(op.f('ix_cotizacion_items_sku_id'), 'cotizacion_items', ['sku_id'], unique=False)
    
    tipo_persona = postgresql.ENUM('LEAD', 'CLIENTE', 'EMPLEADO', name='tipopersona')
    tipo_persona.create(op.get_bind())
    
    op.add_column('personas', sa.Column('tipo_persona', tipo_persona, nullable=False, server_default='LEAD'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personas', 'tipo_persona')
    op.drop_index(op.f('ix_cotizacion_items_sku_id'), table_name='cotizacion_items')
    op.drop_index(op.f('ix_cotizacion_items_cotizacion_id'), table_name='cotizacion_items')
    op.drop_table('cotizacion_items')
    op.drop_index(op.f('ix_cotizaciones_persona_id'), table_name='cotizaciones')
    op.drop_table('cotizaciones')
    
    tipo_persona = postgresql.ENUM('LEAD', 'CLIENTE', 'EMPLEADO', name='tipopersona')
    tipo_persona.drop(op.get_bind())
    # ### end Alembic commands ###
