"""Add transporte_preferido to personas

Revision ID: b78aac609d67
Revises: 2c77585b56bd
Create Date: 2026-06-16 19:21:28.455777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b78aac609d67'
down_revision: Union[str, None] = '2c77585b56bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('productimage')
    op.add_column('personas', sa.Column('transporte_preferido', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personas', 'transporte_preferido')
    op.create_table('productimage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_main', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ui_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('config_match', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='productimage_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='productimage_pkey')
    )
    # ### end Alembic commands ###
