"""initial_migration

Revision ID: f925534d3a76
Revises: 
Create Date: 2026-05-07 12:50:11.607287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f925534d3a76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.drop_table('user')
    op.drop_table('categoryattributelink')
    op.drop_table('productimage')
    op.drop_table('templateattributelink')
    op.drop_index('ix_attributetemplate_name', table_name='attributetemplate')
    op.drop_table('attributetemplate')
    op.alter_column('attribute', 'is_filterable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('attribute', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('attribute', 'value_structure',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('attribute', 'domain',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_column('attribute', 'type')
    op.drop_column('attribute', 'values')
    op.alter_column('auditoria_acceso_sensible', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('auditoria_acceso_sensible', 'detalle',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index('idx_auditoria_actor', table_name='auditoria_acceso_sensible')
    op.drop_index('idx_auditoria_persona_fecha', table_name='auditoria_acceso_sensible')
    op.create_index(op.f('ix_auditoria_acceso_sensible_actor_cuenta_id'), 'auditoria_acceso_sensible', ['actor_cuenta_id'], unique=False)
    op.create_index(op.f('ix_auditoria_acceso_sensible_persona_afectada_id'), 'auditoria_acceso_sensible', ['persona_afectada_id'], unique=False)
    op.create_index(op.f('ix_auditoria_acceso_sensible_recurso_accedido_id'), 'auditoria_acceso_sensible', ['recurso_accedido_id'], unique=False)
    op.create_index(op.f('ix_auditoria_acceso_sensible_timestamp'), 'auditoria_acceso_sensible', ['timestamp'], unique=False)
    op.alter_column('category', 'level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('category', 'path',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('category', 'is_filterable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint('category_template_id_fkey', 'category', type_='foreignkey')
    op.drop_constraint('category_parent_id_fkey', 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'category', ['parent_id'], ['id'])
    op.drop_column('category', 'template_id')
    op.alter_column('contratos_legales', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_contratos_vigente', table_name='contratos_legales', postgresql_where='(fecha_fin IS NULL)')
    op.alter_column('cuentas_acceso', 'intentos_fallidos',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('cuentas_acceso', 'ultimo_acceso',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('cuentas_acceso', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('cuentas_acceso_email_corporativo_key', 'cuentas_acceso', type_='unique')
    op.drop_index('idx_cuentas_email', table_name='cuentas_acceso')
    op.create_index(op.f('ix_cuentas_acceso_email_corporativo'), 'cuentas_acceso', ['email_corporativo'], unique=True)
    op.alter_column('datos_bancarios', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('estado_cuenta', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('historial_remuneraciones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_remuneraciones_vigente', table_name='historial_remuneraciones', postgresql_where='(fecha_fin IS NULL)')
    op.alter_column('homepagesection', 'page',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'homepage'::character varying"))
    op.create_index(op.f('ix_homepagesection_page'), 'homepagesection', ['page'], unique=False)
    op.alter_column('perfiles_cliente', 'descuento_porcentaje',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('perfiles_cliente', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('permisos', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint('permisos_recurso_accion_key', 'permisos', type_='unique')
    op.alter_column('personas', 'estado',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'ACTIVO'::character varying"))
    op.alter_column('personas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_personas_rut', table_name='personas')
    op.drop_constraint('personas_rut_key', 'personas', type_='unique')
    op.create_index(op.f('ix_personas_rut'), 'personas', ['rut'], unique=True)
    op.drop_constraint('politicas_acceso_permiso_id_fkey', 'politicas_acceso', type_='foreignkey')
    op.create_foreign_key(None, 'politicas_acceso', 'permisos', ['permiso_id'], ['id'])
    op.alter_column('product', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('product', 'extras',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_product_is_deleted'), 'product', ['is_deleted'], unique=False)
    op.add_column('productoption', sa.Column('characteristic_id', sa.Integer(), nullable=False))
    op.drop_constraint('productoption_attribute_id_fkey', 'productoption', type_='foreignkey')
    op.create_foreign_key(None, 'productoption', 'attribute', ['characteristic_id'], ['id'])
    op.drop_column('productoption', 'attribute_id')
    op.drop_column('sku', 'image_urls')
    op.alter_column('specificationcharacteristiclink', 'allowed_values',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('usuario_permisos_directos', 'fecha_inicio',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('usuario_permisos_directos', 'fecha_fin',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint('usuario_permisos_directos_cuenta_id_fkey', 'usuario_permisos_directos', type_='foreignkey')
    op.drop_constraint('usuario_permisos_directos_permiso_id_fkey', 'usuario_permisos_directos', type_='foreignkey')
    op.create_foreign_key(None, 'usuario_permisos_directos', 'permisos', ['permiso_id'], ['id'])
    op.create_foreign_key(None, 'usuario_permisos_directos', 'cuentas_acceso', ['cuenta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario_permisos_directos', type_='foreignkey')
    op.drop_constraint(None, 'usuario_permisos_directos', type_='foreignkey')
    op.create_foreign_key('usuario_permisos_directos_permiso_id_fkey', 'usuario_permisos_directos', 'permisos', ['permiso_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('usuario_permisos_directos_cuenta_id_fkey', 'usuario_permisos_directos', 'cuentas_acceso', ['cuenta_id'], ['id'], ondelete='CASCADE')
    op.alter_column('usuario_permisos_directos', 'fecha_fin',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('usuario_permisos_directos', 'fecha_inicio',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('specificationcharacteristiclink', 'allowed_values',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.add_column('sku', sa.Column('image_urls', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True))
    op.add_column('productoption', sa.Column('attribute_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'productoption', type_='foreignkey')
    op.create_foreign_key('productoption_attribute_id_fkey', 'productoption', 'attribute', ['attribute_id'], ['id'])
    op.drop_column('productoption', 'characteristic_id')
    op.drop_index(op.f('ix_product_is_deleted'), table_name='product')
    op.alter_column('product', 'extras',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('product', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'politicas_acceso', type_='foreignkey')
    op.create_foreign_key('politicas_acceso_permiso_id_fkey', 'politicas_acceso', 'permisos', ['permiso_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_personas_rut'), table_name='personas')
    op.create_unique_constraint('personas_rut_key', 'personas', ['rut'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_personas_rut', 'personas', ['rut'], unique=False)
    op.alter_column('personas', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('personas', 'estado',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'ACTIVO'::character varying"))
    op.create_unique_constraint('permisos_recurso_accion_key', 'permisos', ['recurso', 'accion'], postgresql_nulls_not_distinct=False)
    op.alter_column('permisos', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('perfiles_cliente', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('perfiles_cliente', 'descuento_porcentaje',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.drop_index(op.f('ix_homepagesection_page'), table_name='homepagesection')
    op.alter_column('homepagesection', 'page',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'homepage'::character varying"))
    op.create_index('idx_remuneraciones_vigente', 'historial_remuneraciones', ['persona_id'], unique=False, postgresql_where='(fecha_fin IS NULL)')
    op.alter_column('historial_remuneraciones', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('estado_cuenta', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('datos_bancarios', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_cuentas_acceso_email_corporativo'), table_name='cuentas_acceso')
    op.create_index('idx_cuentas_email', 'cuentas_acceso', ['email_corporativo'], unique=False)
    op.create_unique_constraint('cuentas_acceso_email_corporativo_key', 'cuentas_acceso', ['email_corporativo'], postgresql_nulls_not_distinct=False)
    op.alter_column('cuentas_acceso', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('cuentas_acceso', 'ultimo_acceso',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('cuentas_acceso', 'intentos_fallidos',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index('idx_contratos_vigente', 'contratos_legales', ['persona_id'], unique=False, postgresql_where='(fecha_fin IS NULL)')
    op.alter_column('contratos_legales', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('category', sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key('category_parent_id_fkey', 'category', 'category', ['parent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('category_template_id_fkey', 'category', 'attributetemplate', ['template_id'], ['id'])
    op.alter_column('category', 'is_filterable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('category', 'path',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('category', 'level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_auditoria_acceso_sensible_timestamp'), table_name='auditoria_acceso_sensible')
    op.drop_index(op.f('ix_auditoria_acceso_sensible_recurso_accedido_id'), table_name='auditoria_acceso_sensible')
    op.drop_index(op.f('ix_auditoria_acceso_sensible_persona_afectada_id'), table_name='auditoria_acceso_sensible')
    op.drop_index(op.f('ix_auditoria_acceso_sensible_actor_cuenta_id'), table_name='auditoria_acceso_sensible')
    op.create_index('idx_auditoria_persona_fecha', 'auditoria_acceso_sensible', ['persona_afectada_id', sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_auditoria_actor', 'auditoria_acceso_sensible', ['actor_cuenta_id'], unique=False)
    op.alter_column('auditoria_acceso_sensible', 'detalle',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditoria_acceso_sensible', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('attribute', sa.Column('values', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True))
    op.add_column('attribute', sa.Column('type', postgresql.ENUM('text', 'select', 'multiselect', 'number', 'color', name='attributetype'), server_default=sa.text("'text'::attributetype"), autoincrement=False, nullable=True))
    op.alter_column('attribute', 'domain',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('attribute', 'value_structure',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('attribute', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('attribute', 'is_filterable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_table('attributetemplate',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('attributetemplate_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='attributetemplate_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_attributetemplate_name', 'attributetemplate', ['name'], unique=True)
    op.create_table('templateattributelink',
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attribute_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute.id'], name='templateattributelink_attribute_id_fkey'),
    sa.ForeignKeyConstraint(['template_id'], ['attributetemplate.id'], name='templateattributelink_template_id_fkey'),
    sa.PrimaryKeyConstraint('template_id', 'attribute_id', name='templateattributelink_pkey')
    )
    op.create_table('productimage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_main', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ui_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('config_match', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='productimage_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='productimage_pkey')
    )
    op.create_table('categoryattributelink',
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attribute_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute.id'], name='categoryattributelink_attribute_id_fkey'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='categoryattributelink_category_id_fkey'),
    sa.PrimaryKeyConstraint('category_id', 'attribute_id', name='categoryattributelink_pkey')
    )
    op.create_table('user',
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('ADMIN', 'WORKER', 'CLIENT', name='userrole'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
